replicaCount: 2

image:
  repository: thegomina/hygie-ai-bmp-service
  pullPolicy: IfNotPresent
  tag: "0.1.0"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: ""
  host: ""
  annotations: {}
  tls:
    enabled: false
    secretName: ""

metrics:
  serviceMonitor:
    enabled: true
    namespace: ""
    interval: 15s
