repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    - id: black
      language_version: python3.12
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black"]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      args: [
        "--max-line-length=88",
        "--exclude=.venv,__pycache__,node_modules,backend/microservices,backend/bmp_service/scripts",
        "--ignore=E203,E402,E501,F401,F403,F404",
        "--exit-zero"
      ]
-   repo: https://github.com/pycqa/autoflake
    rev: v1.7.0
    hooks:
    - id: autoflake
      args: ["--remove-all-unused-imports", "--ignore-init-module-imports", "--remove-unused-variables"]
default_language_version:
  python: python3.12
exclude: '^(\.venv|node_modules|backend/microservices|backend/bmp_service/scripts)/'
