version: "3.9"
services:
  api:
    build:
      context: ./backend/bmp_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  front:
    build: ./frontend/hygie-ai-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
