global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:8000']
  - job_name: 'bmp_service'
    static_configs:
      - targets: ['bmp_service:8000']
