apiVersion: v1
kind: Service
metadata:
  name: {{ include "bmp-service.fullname" . }}
  labels:
    {{- include "bmp-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "bmp-service.fullname" . }}
